#https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#default-behavior
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pix-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pix-backend
  minReplicas: 1
  maxReplicas: 10
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 20
        periodSeconds: 10
      selectPolicy: Max